import React from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { FiBookOpen, FiCpu, FiTerminal, FiPieChart, FiAward, FiArrowLeft } from "react-icons/fi";

export default function FeaturesPage() {
  const featuresList = [
    {
      icon: <FiBookOpen className="w-8 h-8" />,
      title: "Placement Mock Exams",
      subtitle: "Custom-configured assessments with time pressure constraints",
      desc: "Practice with category-specific MCQ, True/False, and Multi-select exam papers generated dynamically. Includes adaptive retake prioritization (Unseen -> Incorrect -> Older) to optimize revision cycles.",
      color: "from-blue-500/20 to-indigo-500/20 text-blue-500 border-blue-500/10"
    },
    {
      icon: <FiCpu className="w-8 h-8" />,
      title: "AI-Graded Mock Interviews",
      subtitle: "Real-time simulated technical and behavioral panels",
      desc: "Simulate a live interview environment with category-specific questions. Answer prompts using structured dictation, and receive question-by-question scoring, strengths, weaknesses, and ideal answers generated by GenAI.",
      color: "from-purple-500/20 to-pink-500/20 text-purple-500 border-purple-500/10"
    },
    {
      icon: <FiTerminal className="w-8 h-8" />,
      title: "Coding Review Workspace",
      subtitle: "Multi-language programming workspace with automated reviews",
      desc: "Solve coding challenges on a premium split-screen compiler. Get instantaneous review feedback detailing logic bugs, complexity analysis (Time & Space complexity), and fully optimized model solutions.",
      color: "from-emerald-500/20 to-teal-500/20 text-emerald-500 border-emerald-500/10"
    },
    {
      icon: <FiPieChart className="w-8 h-8" />,
      title: "Placement Analytics & Mastery",
      subtitle: "Detailed performance tracking and mastery logs",
      desc: "Track preparation progress with daily learning streaks, cumulative practice hours, category-wise performance distributions, and subtopic mastery tracking percentages.",
      color: "from-amber-500/20 to-orange-500/20 text-amber-500 border-amber-500/10"
    },
    {
      icon: <FiAward className="w-8 h-8" />,
      title: "AI Placement Recommendations",
      subtitle: "Personalized path suggestions and readiness metrics",
      desc: "Receive tailored learning tips on your dashboard derived from performance trends. View your predicted placement readiness tier to know when you are fully ready to apply.",
      color: "from-cyan-500/20 to-sky-500/20 text-cyan-500 border-cyan-500/10"
    }
  ];

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-12">
      {/* Back button */}
      <Link
        to="/"
        className="inline-flex items-center space-x-1.5 text-slate-500 hover:text-slate-800 dark:hover:text-white text-xs font-bold transition-all"
      >
        <FiArrowLeft />
        <span>Back to Home</span>
      </Link>

      <div className="space-y-2">
        <h2 className="text-3xl font-extrabold text-slate-800 dark:text-white tracking-tight">
          Explore PrepMaster AI Features
        </h2>
        <p className="text-sm text-slate-500 dark:text-slate-400 font-semibold">
          Accelerate your campus drive and MNC preparation with advanced AI tools.
        </p>
      </div>

      {/* Feature List Cards */}
      <div className="space-y-8">
        {featuresList.map((f, idx) => (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.08 }}
            key={idx}
            className="p-8 rounded-3xl bg-white dark:bg-darkCard border border-slate-100 dark:border-darkBorder shadow-premium flex flex-col md:flex-row gap-6 hover:shadow-lg transition-all"
          >
            {/* Feature Icon */}
            <div className={`p-5 rounded-2xl border bg-gradient-to-tr ${f.color} flex-shrink-0 w-16 h-16 flex items-center justify-center`}>
              {f.icon}
            </div>

            {/* Description */}
            <div className="space-y-2">
              <h3 className="text-xl font-extrabold text-slate-850 dark:text-white">
                {f.title}
              </h3>
              <h4 className="text-xs font-bold text-primary-500 uppercase tracking-wider">
                {f.subtitle}
              </h4>
              <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed font-semibold pt-2">
                {f.desc}
              </p>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
