import { jsPDF } from 'jspdf';

/**
 * Generates and downloads a professional PDF report of an interview session
 * @param {object} session The interview session object
 * @param {string} username The name of the candidate
 */
export function exportInterviewSetToPDF(session, username = "Future Engineer") {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageHeight = 297;
  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = 25;

  // Helper to check page bounds and create new page if necessary
  const checkPageBounds = (neededHeight) => {
    if (yPos + neededHeight > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
      drawFooter();
    }
  };

  // Helper to draw clean header styling
  const drawHeader = () => {
    // Top primary accent bar
    doc.setFillColor(37, 99, 235); // primary-600
    doc.rect(0, 0, pageWidth, 5, 'F');
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text("InterviewAce AI", margin, yPos);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text("Smart Interview Preparation Platform", margin, yPos + 6);
    yPos += 14;
  };

  // Helper to draw page number and footer
  const drawFooter = () => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(`Generated by InterviewAce AI for ${username}`, margin, pageHeight - 10);
    const pageNum = doc.getNumberOfPages();
    doc.text(`Page ${pageNum}`, pageWidth - margin - 10, pageHeight - 10);
  };

  // 1. Draw Header
  drawHeader();

  // 2. Draw Candidate Profile & Session Details Table
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, yPos, contentWidth, 32, 3, 3, 'FD');

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59); // slate-800
  
  doc.text("CANDIDATE PROFILE", margin + 5, yPos + 6);
  doc.text("SESSION SUMMARY", margin + contentWidth / 2 + 5, yPos + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // slate-600

  // Left Column
  doc.text(`Name: ${username}`, margin + 5, yPos + 14);
  doc.text(`Target Role: ${session.role}`, margin + 5, yPos + 20);
  doc.text(`Prep Date: ${session.date || new Date().toLocaleDateString()}`, margin + 5, yPos + 26);

  // Right Column
  doc.text(`Difficulty Level: ${session.difficulty}`, margin + contentWidth / 2 + 5, yPos + 14);
  doc.text(`Question Type: ${session.questionType}`, margin + contentWidth / 2 + 5, yPos + 20);
  doc.text(`Total Questions: ${session.questions?.length || 0}`, margin + contentWidth / 2 + 5, yPos + 26);

  yPos += 42;

  // 3. Draw Section title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text("Interview Questions & Answers", margin, yPos);
  
  // Underline
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos + 2, margin + 25, yPos + 2);
  yPos += 10;

  // 4. Render Questions
  session.questions?.forEach((q, idx) => {
    // Check if we need a new page for the next question header
    checkPageBounds(20);

    // Question number and title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(37, 99, 235); // Primary-600
    
    const qHeader = `Q${idx + 1}. ${q.question}`;
    const splitQHeader = doc.splitTextToSize(qHeader, contentWidth);
    doc.text(splitQHeader, margin, yPos);
    yPos += (splitQHeader.length * 5);

    // Key concepts
    if (q.keyConcepts) {
      doc.setFont("helvetica", "oblique");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Concepts tested: ${q.keyConcepts}`, margin, yPos);
      yPos += 5;
    }

    // Model Answer block
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85); // Slate-700
    
    const modelAnsPrefix = "Model Answer: ";
    const ansText = q.modelAnswer || q.expectedAnswer || "No answer provided.";
    
    // Split model answer text
    const splitAnsText = doc.splitTextToSize(ansText, contentWidth - 5);
    
    // Calculate total height needed for answer + tips box
    const ansHeight = splitAnsText.length * 4.5;
    const tipsText = q.tips || "Review fundamental concepts regarding this topic.";
    const splitTipsText = doc.splitTextToSize(`Interview Tip: ${tipsText}`, contentWidth - 10);
    const tipsBoxHeight = (splitTipsText.length * 4) + 6;
    
    // Check page bounds before writing body answer block
    checkPageBounds(ansHeight + tipsBoxHeight + 10);

    // Draw bullet/bar for model answer
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.7);
    doc.line(margin + 1, yPos, margin + 1, yPos + ansHeight - 2);

    doc.text(splitAnsText, margin + 4, yPos + 1);
    yPos += ansHeight + 3;

    // Draw Box for Interview Tips
    doc.setFillColor(240, 246, 255); // Very light primary-50
    doc.setDrawColor(191, 219, 254); // primary-200
    doc.roundedRect(margin, yPos, contentWidth, tipsBoxHeight, 1.5, 1.5, 'FD');

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(29, 78, 216); // primary-700
    doc.text(splitTipsText, margin + 5, yPos + 5);
    yPos += tipsBoxHeight + 10;
  });

  // Draw footer for the first page / all pages
  for (let i = 1; i <= doc.getNumberOfPages(); i++) {
    doc.setPage(i);
    drawFooter();
  }

  // Save the PDF
  const filename = `InterviewAce_${session.role.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
  doc.save(filename);
}
